<?php

class Clockworkgeek_Extrarestful_Model_Api2_Product_Crosssell_Rest_Customer_V1 extends Clockworkgeek_Extrarestful_Model_Api2_Product_Crosssell
{
    use Clockworkgeek_Extrarestful_Model_Api2_Product_CustomerTrait;
}
