<?php

class Clockworkgeek_Extrarestful_Model_Api2_Product_Related_Rest_Guest_V1 extends Clockworkgeek_Extrarestful_Model_Api2_Product_Related
{
    use Clockworkgeek_Extrarestful_Model_Api2_Product_GuestTrait;
}
